# Generated by Django 4.2.28 on 2026-02-27 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('other_relative', 'Other Relative'), ('non_relative', 'Non-Relative')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='National ID')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Has disability')),
                ('is_employed', models.BooleanField(default=False)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_name', models.CharField(max_length=255)),
                ('number_of_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('main_income_source', models.CharField(blank=True, max_length=255)),
                ('consistent_income_6months', models.BooleanField(default=False)),
                ('children_under_18', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_savings_group_member', models.BooleanField(default=False, verbose_name='Part of savings group')),
                ('residence_type', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('informal', 'Informal/Slum'), ('other', 'Other')], default='informal', max_length=20)),
                ('estimated_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('household_assets', models.TextField(blank=True, help_text='List household assets')),
                ('can_pay_emergency', models.BooleanField(default=False, verbose_name='Can pay emergency expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Households',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('vocational', 'Vocational')], default='primary', max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, help_text='Upload a recent photo of the child', null=True, upload_to='children/photos/%Y/%m/%d/')),
                ('child_id', models.CharField(help_text='Unique child identifier', max_length=50, unique=True)),
                ('chronic_medical_condition', models.TextField(blank=True, help_text='Any ongoing medical conditions', verbose_name='Chronic medical condition')),
                ('income_provider', models.CharField(blank=True, help_text='Primary income provider for the household', max_length=255, verbose_name='Who provides most household income')),
                ('education_payer', models.CharField(blank=True, help_text='Person/organization paying for education', max_length=255, verbose_name='Who pays for education')),
                ('medical_payer', models.CharField(blank=True, help_text='Person/organization paying for medical expenses', max_length=255, verbose_name='Who pays for medical bills')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregivers', models.ManyToManyField(blank=True, related_name='children', to='children.caregiver')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='children.household')),
                ('projects', models.ManyToManyField(blank=True, related_name='enrolled_children', to='children.project')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='children.school')),
            ],
            options={
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['child_id'], name='children_ch_child_i_3b6679_idx'), models.Index(fields=['date_of_birth'], name='children_ch_date_of_8a51a3_idx'), models.Index(fields=['last_name', 'first_name'], name='children_ch_last_na_7fe854_idx'), models.Index(fields=['registration_date'], name='children_ch_registr_7fffbc_idx')],
            },
        ),
    ]
