# Generated by Django 4.2.28 on 2026-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('education', 'Education Mentor'), ('healthcare', 'Healthcare'), ('counseling', 'Counseling'), ('logistics', 'Logistics'), ('fundraising', 'Fundraising'), ('general', 'General Volunteer')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers/photos/')),
                ('hours_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='children_vo_email_443479_idx'), models.Index(fields=['status', 'role'], name='children_vo_status_9bd421_idx')],
            },
        ),
    ]
