# Generated by Django 4.2.28 on 2026-02-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='estimated_monthly_income',
            field=models.FloatField(default=0, help_text='Estimated monthly household income'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hours_contributed',
            field=models.FloatField(default=0),
        ),
    ]
